language: generic

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: 's3copier'
  skip_cleanup: true
  acl: public_read
  local-dir: folder2

branches:
  only:
    - development